services:
  app:
    build:
      context: .
      dockerfile: Dockerfile.staging
    ports:
      - "3000:3000"
    environment:
      - MONGO_URI=${MONGO_URI}
      - PORT=3000
    env_file:
      - .env
