# Dockerfile.production
FROM node:18

WORKDIR /app

COPY package*.json ./

RUN npm ci --omit=dev

COPY . .

COPY .env.production .env.production

EXPOSE 8080

ENV NODE_ENV=production

CMD ["node", "main.js"]
